// Mock data for the app

export const currentUser = {
  id: '1',
  username: 'johndoe',
  name: 'John Doe',
  avatar: 'https://i.pravatar.cc/150?img=12',
  placesVisited: 47,
  friendsCount: 128,
  rank: 15,
  totalPosts: 89,
};

export const mockPosts = [
  {
    id: '1',
    userId: '2',
    username: 'sarah_travels',
    userAvatar: 'https://i.pravatar.cc/150?img=1',
    placeName: 'Santorini, Greece',
    location: 'Greece',
    image: 'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800',
    description: 'The most beautiful sunset I\'ve ever witnessed. The white and blue architecture against the Aegean Sea is simply breathtaking.',
    likes: 234,
    comments: 18,
    timestamp: '2 hours ago',
    isLiked: false,
  },
  {
    id: '2',
    userId: '3',
    username: 'wanderlust_mike',
    userAvatar: 'https://i.pravatar.cc/150?img=5',
    placeName: 'Tokyo, Japan',
    location: 'Japan',
    image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800',
    description: 'Exploring the vibrant streets of Shibuya. The energy here is incredible!',
    likes: 189,
    comments: 12,
    timestamp: '5 hours ago',
    isLiked: true,
  },
  {
    id: '3',
    userId: '4',
    username: 'emily_adventures',
    userAvatar: 'https://i.pravatar.cc/150?img=9',
    placeName: 'Machu Picchu, Peru',
    location: 'Peru',
    image: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800',
    description: 'Hiked the Inca Trail and finally made it to this wonder of the world. Worth every step!',
    likes: 456,
    comments: 34,
    timestamp: '1 day ago',
    isLiked: false,
  },
  {
    id: '4',
    userId: '5',
    username: 'travel_dan',
    userAvatar: 'https://i.pravatar.cc/150?img=15',
    placeName: 'Iceland',
    location: 'Iceland',
    image: 'https://images.unsplash.com/photo-1504829857797-ddff29c27927?w=800',
    description: 'Northern Lights dancing across the sky. Nature never fails to amaze me.',
    likes: 567,
    comments: 42,
    timestamp: '2 days ago',
    isLiked: true,
  },
  {
    id: '5',
    userId: '6',
    username: 'lisa_explorer',
    userAvatar: 'https://i.pravatar.cc/150?img=20',
    placeName: 'Bali, Indonesia',
    location: 'Indonesia',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800',
    description: 'Peaceful mornings by the rice terraces. This place is paradise.',
    likes: 312,
    comments: 28,
    timestamp: '3 days ago',
    isLiked: false,
  },
];

export const mockUsers = [
  {
    id: '2',
    username: 'sarah_travels',
    name: 'Sarah Johnson',
    avatar: 'https://i.pravatar.cc/150?img=1',
    placesVisited: 89,
    rank: 3,
    isFriend: true,
  },
  {
    id: '3',
    username: 'wanderlust_mike',
    name: 'Michael Chen',
    avatar: 'https://i.pravatar.cc/150?img=5',
    placesVisited: 76,
    rank: 7,
    isFriend: true,
  },
  {
    id: '4',
    username: 'emily_adventures',
    name: 'Emily Rodriguez',
    avatar: 'https://i.pravatar.cc/150?img=9',
    placesVisited: 95,
    rank: 1,
    isFriend: false,
  },
  {
    id: '5',
    username: 'travel_dan',
    name: 'Daniel Kim',
    avatar: 'https://i.pravatar.cc/150?img=15',
    placesVisited: 82,
    rank: 5,
    isFriend: true,
  },
  {
    id: '6',
    username: 'lisa_explorer',
    name: 'Lisa Anderson',
    avatar: 'https://i.pravatar.cc/150?img=20',
    placesVisited: 71,
    rank: 12,
    isFriend: false,
  },
  {
    id: '7',
    username: 'adventure_alex',
    name: 'Alex Martinez',
    avatar: 'https://i.pravatar.cc/150?img=30',
    placesVisited: 68,
    rank: 18,
    isFriend: false,
  },
];

export const mockRankings = [
  {
    id: '4',
    username: 'emily_adventures',
    name: 'Emily Rodriguez',
    avatar: 'https://i.pravatar.cc/150?img=9',
    placesVisited: 95,
    rank: 1,
    countries: ['Peru', 'Japan', 'Thailand', 'Italy', 'Australia', 'New Zealand'],
  },
  {
    id: '8',
    username: 'world_explorer',
    name: 'David Thompson',
    avatar: 'https://i.pravatar.cc/150?img=40',
    placesVisited: 92,
    rank: 2,
    countries: ['USA', 'Canada', 'Mexico', 'Brazil', 'Argentina', 'Chile'],
  },
  {
    id: '2',
    username: 'sarah_travels',
    name: 'Sarah Johnson',
    avatar: 'https://i.pravatar.cc/150?img=1',
    placesVisited: 89,
    rank: 3,
    countries: ['Greece', 'Turkey', 'Spain', 'Portugal', 'Morocco'],
  },
  {
    id: '9',
    username: 'globetrotter',
    name: 'Jessica Lee',
    avatar: 'https://i.pravatar.cc/150?img=25',
    placesVisited: 85,
    rank: 4,
    countries: ['China', 'South Korea', 'Vietnam', 'Cambodia', 'Singapore'],
  },
  {
    id: '5',
    username: 'travel_dan',
    name: 'Daniel Kim',
    avatar: 'https://i.pravatar.cc/150?img=15',
    placesVisited: 82,
    rank: 5,
    countries: ['Iceland', 'Norway', 'Sweden', 'Denmark', 'Finland'],
  },
];

export const mockFriendRequests = [
  {
    id: '10',
    username: 'mountain_lover',
    name: 'Ryan Cooper',
    avatar: 'https://i.pravatar.cc/150?img=35',
    placesVisited: 64,
    rank: 22,
  },
  {
    id: '11',
    username: 'beach_bum',
    name: 'Sophia White',
    avatar: 'https://i.pravatar.cc/150?img=45',
    placesVisited: 58,
    rank: 31,
  },
];

